New Wisotool

diff --git a/tools/wisotool b/tools/wisotool
--- a/tools/wisotool
+++ b/tools/wisotool
@@ -12,7 +12,7 @@
 #---- Constants -------------------------------------------------
 
 # Name of this version of wisotool (YYYYMMDD)
-VERSION=20100323
+VERSION=20100424
 
 early_wine()
 {
@@ -44,6 +44,7 @@ esac
 
 # You can add your own verb to wisotool by creating $WISOTOOL_VERBS/foo.verb
 WISOTOOL_VERBS="${WISOTOOL_VERBS:-$HOME/.wisotool/verbs}"
+mkdir -p "$WISOTOOL_VERBS"
 
 # Internal variables; these locations are not too important
 WISOTOOL_CACHE="${WISOTOOL_CACHE:-$HOME/.wisotoolcache}"
@@ -163,19 +164,23 @@ die_if_user_not_dirowner() {
 usage() {
     set +x
     # WARNING: do not use single quote in any package description; that breaks the gui menu.
+    echo "Script to install games automatically."
     echo "Usage: $0 [options] package [package] ..."
-    echo "This script can catalog your .iso files, and later install"
-    echo "Windows apps from them."
     echo ""
     echo "Options:"
     echo " -q         quieter"
     echo " -v         verbose"
     echo " -V         display Version"
     echo "Packages:"
-    sort "$WISOTOOL_TMP"/menutext
+    sort "$WISOTOOL_VERBS"/menutext
     echo "Pseudopackages:"
-    echo " load          Load a new iso"
-    echo " load=KEY      Load a new iso (with given key; only works from commandline at moment)"
+    echo " load          Load a disc into the iso cache"
+    echo " load=KEY      Load a disc with given key; only works from commandline at moment"
+
+    # Show the other help message, too
+    case $GUI in
+    0) load_help ;;
+    esac
 }
 
 #----------------------------------------------------------------
@@ -650,7 +655,7 @@ verblist_init()
     # Must call this before first call to verblist_add
     file_map="case \$1 in "
     # Clear menu
-    rm -f "$WISOTOOL_TMP"/menutext
+    rm -f "$WISOTOOL_VERBS"/menutext
 }
 
 verblist_finish()
@@ -663,7 +668,7 @@ verblist_finish()
 menu_add() {
     verbname=$1
     description="$2"
-    printf " %-16s %s\n" $verbname "$description" >> "$WISOTOOL_TMP"/menutext
+    printf " %-16s %s\n" $verbname "$description" >> "$WISOTOOL_VERBS"/menutext
 }
 
 # Add a new verb
@@ -671,21 +676,27 @@ verblist_add()
 {
     # Usage: verblist_add verbname "description" file1 file2 ...
     verbname=$1
+    description="$2"
     shift
-    description="$1"
     shift
-    menu_add $verbname "$description"
+    present=''
+    test $verbname != 'help' && present=' [loaded]'
     for file
     do
        file_map="$file_map $file) echo $verbname;; "
+       if ! test -f "$WISOTOOL_CACHE"/$verbname/$file
+       then
+           present=''
+       fi
     done
+    menu_add $verbname "$description$present"
 }
 
 # Returns true if given verb is in the list
 verblist_is_legal_verb()
 {
   verb=$1
-  awk '{print $1}' < "$WISOTOOL_TMP"/menutext > "$WISOTOOL_TMP"/verbs
+  awk '{print $1}' < "$WISOTOOL_VERBS"/menutext > "$WISOTOOL_TMP"/verbs
   if grep "^$verb$" "$WISOTOOL_TMP"/verbs > /dev/null
   then
       return 0
@@ -733,7 +744,7 @@ verblist_init
 
 #----------------------------------------------------------------
 
-verblist_add 3dmark2000 "3DMark2000 (MadOnion.com, 2000)" 3dmark2000_v11_100308.exe
+verblist_add 3dmark2000 "3DMark2000 (MadOnion.com, 2000) [download]" 3dmark2000_v11_100308.exe
 
 load_3dmark2000() {
     load_autohotkey
@@ -771,7 +782,7 @@ load_3dmark2000() {
 
 #----------------------------------------------------------------
 
-verblist_add 3dmark2001 "3DMark2001 (MadOnion.com, 2001)" 3dmark2000_v11_100308.exe
+verblist_add 3dmark2001 "3DMark2001 (MadOnion.com, 2001) [download]" 3dmark2000_v11_100308.exe
 
 load_3dmark2001() {
     load_autohotkey
@@ -809,7 +820,7 @@ load_3dmark2001() {
 
 #----------------------------------------------------------------
 
-verblist_add 3dmark03 "3D Mark 03 (Futuremark, 2003)" 3DMark03_v360_1901.exe
+verblist_add 3dmark03 "3D Mark 03 (Futuremark, 2003) [download]" 3DMark03_v360_1901.exe
 
 load_3dmark03() {
     load_autohotkey
@@ -854,7 +865,7 @@ load_3dmark03() {
 
 #----------------------------------------------------------------
 
-verblist_add 3dmark05 "3D Mark 05 (Futuremark, 2005)" 3DMark05_v130_1901.exe
+verblist_add 3dmark05 "3D Mark 05 (Futuremark, 2005) [download]" 3DMark05_v130_1901.exe
 
 load_3dmark05() {
     load_autohotkey
@@ -891,7 +902,7 @@ load_3dmark05() {
 
 #----------------------------------------------------------------
 
-verblist_add 3dmark06 "3D Mark 06 (Futuremark, 2006)" 3DMark06_v120_1901.exe
+verblist_add 3dmark06 "3D Mark 06 (Futuremark, 2006) [download]" 3DMark06_v120_1901.exe
 
 load_3dmark06() {
     load_autohotkey
@@ -943,12 +954,20 @@ verblist_add assassinscreed "Assassins Creed (Ubisoft, 2008)" a62112860423b32bf3
 load_assassinscreed() {
     load_autohotkey
 
+    if workaround_wine_bug 22392
+    then
+        # Don't hang at a dialog box when Detection crashes
+        sh "$WINETRICKS" nocrashdialog
+    fi
+
     iso_mount "$WISOTOOL_CACHE"/$PACKAGE/a62112860423b32bf3ea77df6f5fe0b60c772de2.iso
     ahk_do "
         run ${ISO_MOUNT_LETTER}:setup.exe
         SetTitleMatchMode, 2
         winwait, InstallShield Wizard, Language
-        ControlClick Next, InstallShield Wizard
+        ; wine bug? - clicking on Next does nothing until you move the mouse over the installer window
+        ;ControlClick Next, InstallShield Wizard
+        Send {Enter}
         winwait, InstallShield Wizard, Welcome
         ControlClick Next, InstallShield Wizard
         winwait, InstallShield Wizard, License
@@ -973,7 +992,7 @@ verblist_add baldursgate2       "Baldurs Gate 2 - Shadows of Amn (Bioware, 2000)
   cc9359dce1a7be6c64bb6f8e6dea6d14d4a5f716.iso \
   429872605dad10433c3c581a1c11eba4d0988c46.iso \
   a6d18fcd7d16ddafbda7aa028b117566b1e09d2a.iso \
-  94ed41768949c89a1a6479305f00a9cee1d2dcd5.iso.iso
+  94ed41768949c89a1a6479305f00a9cee1d2dcd5.iso
 
 load_baldursgate2() {
     load_autohotkey
@@ -1002,35 +1021,118 @@ load_baldursgate2() {
     iso_mount "$WISOTOOL_CACHE"/$PACKAGE/cc9359dce1a7be6c64bb6f8e6dea6d14d4a5f716.iso
     
     ahk_do "
+        SetTitleMatchMode, 2
         run "$WISOTOOL_CACHE"/$PACKAGE/tempcd/setup.exe
         winwait, Baldur's Gate, Welcome to the Baldur's Gate
-        send {N}
+        sleep 1000
+        ControlClick, Button1, Baldur's Gate, Welcome to the Baldur's Gate
         winwait, Baldur's Gate, Please read the following License Agreement
-        sleep 500
-        ControlClick, &Yes, Baldur's Gate, Please read the following License Agreement
+        sleep 1000
+        ControlClick, Button2, Baldur's Gate, Please read the following License Agreement
         winwait, Baldur's Gate, Setup will install Baldur's Gate
-        send {N}
+        sleep 1000
+        ControlClick, Button1, Baldur's Gate, Setup will install Baldur's Gate
         winwait, Baldur's Gate, Click the type of Setup you prefer
+        sleep 1000
+        ControlClick, Listbox1, Baldur's Gate, Click the type of Setup you prefer
         send {F}
-        send {Enter}
+        ControlClick, Button2, Baldur's Gate, Click the type of Setup you prefer
         winwait, Baldur's Gate, Setup will add program icons
-        sleep 500
-        send {Enter}
+        sleep 1000
+        ControlClick, Button2, Baldur's Gate, Setup will add program icons
         winwait, Setup Needs The Next Disk
+        sleep 1000
         Send {Home}
         Send {Shift down}
         Send {End}
         Send I:{Enter}
         winwait, Information
-        Send {Enter}
+        sleep 1000
+        ControlClick, Button1, Information
         Sleep 5000
         process, wait, Promo.exe, 5
         promopid = %ErrorLevel%
         winclose, ahk_pid %promopid%
         winwait, Baldur's Gate, Setup has finished installing
-        Send {Enter}
+        sleep 1000
+        ControlClick, Button4, Baldur's Gate, Setup has finished installing
         "
+    try chmod +w -R "$WISOTOOL_CACHE"/$PACKAGE/tempcd
     try rm -rf "$WISOTOOL_CACHE"/$PACKAGE/tempcd
+
+    # Install latest patch
+    download baldursgate2 http://downloads.bioware.com/baldursgate2/Baldur%27sGateII-ShadowsofAmnPatchENGLISH.exe 4706c0dc1e282bae14946c87a38e2781f89ebdc4
+    # AHK doesn't like its name...
+    try cp -f "$WISOTOOL_CACHE/baldursgate2/Baldur%27sGateII-ShadowsofAmnPatchENGLISH.exe" "$WISOTOOL_CACHE/baldursgate2/baldurs_gate_2_patch.exe"
+
+    cd $WISOTOOL_CACHE/baldursgate2
+    ahk_do "
+        SetTitleMatchMode, 2
+        run, baldurs_gate_2_patch.exe
+        winwait InstallShield Wizard, Welcome to the InstallShield Wizard
+        sleep 1000
+        ControlClick Button1, InstallShield Wizard, Welcome to the InstallShield Wizard
+        winwait InstallShield Wizard, InstallShield Wizard Complete
+        sleep 1000
+        ControlClick Button4, InstallShield Wizard, InstallShield Wizard Complete
+        exit"
+    cd -
+    try rm "$WISOTOOL_CACHE/baldursgate2/baldurs_gate_2_patch.exe"
+    
+    if workaround_wine_bug 22482
+    then
+        sh "$WINETRICKS" -q ddr=opengl
+        warn "Enabling 3d acceleration in BGConfig.exe will improve performance."
+    fi
+    
+    if workaround_wine_bug 22493
+    then
+        warn "Enabling 3d acceleration in BGConfig.exe will improve performance."
+    fi
+}
+
+#----------------------------------------------------------------
+
+# http://appdb.winehq.org/objectManager.php?sClass=version&iId=9320
+verblist_add bioshock       "Bioshock (2K Games, 2007)" \
+  deaf00ebee6e73aecf38f704c3f516008a68d888.iso
+
+load_bioshock() {
+    load_autohotkey
+    
+    # Bioshock needs MSVCP80.dll to run, which Wine doesn't have yet.
+    sh "$WINETRICKS" -q vcrun2005sp1
+    
+    # Will perform a full install, so no cd's needed
+    iso_mount "$WISOTOOL_CACHE"/$PACKAGE/deaf00ebee6e73aecf38f704c3f516008a68d888.iso
+    
+    # FIXME: fails unless the real DVD is in the drive. Fails on the iso.
+    ahk_do "
+        SetTitleMatchMode, 2
+        run ${ISO_MOUNT_LETTER}:setup.exe
+        winwait, BioShock - InstallShield Wizard, Choose Setup Language
+        sleep 2000
+        ControlClick, Button3, BioShock - InstallShield Wizard, Choose Setup Language
+        ControlClick, Button3, BioShock - InstallShield Wizard, Choose Setup Language ; Installer seems fidgety
+        winwait, BioShock - InstallShield Wizard, Welcome to the InstallShield Wizard for BioShock
+        sleep 1000
+        ControlClick, Button1, BioShock - InstallShield Wizard, Welcome to the InstallShield Wizard for BioShock
+        winwait, BioShock - InstallShield Wizard, Please read the following license agreement carefully
+        sleep 1000
+        ControlClick, Button5, BioShock - InstallShield Wizard, Please read the following license agreement carefully
+        sleep 1000
+        ControlClick, Button2, BioShock - InstallShield Wizard, Please read the following license agreement carefully
+        winwait, BioShock - InstallShield Wizard, Select the setup type to install
+        sleep 1000
+        ControlClick, Button2, BioShock - InstallShield Wizard, Select the setup type to install
+        winwait, BioShock - InstallShield Wizard, Click Install to begin the installation
+        ControlClick, Button1, BioShock - InstallShield Wizard, Click Install to begin the installation
+        winwait, BioShock - InstallShield Wizard, The InstallShield Wizard has successfully installed BioShock
+        sleep 1000
+        ControlClick, Button6, BioShock - InstallShield Wizard, The InstallShield Wizard has successfully installed BioShock
+        sleep 1000
+        ControlClick, Button4, BioShock - InstallShield Wizard, The InstallShield Wizard has successfully installed BioShock
+        "
 }
 
 #----------------------------------------------------------------
@@ -1094,12 +1196,13 @@ load_diablo2() {
     iso_umount
 
     try "$WINE" "$WISOTOOL_CACHE"/diablo2/D2Patch_113c.exe
-    # Dagnabbit, the darn updater starts the game after it updates, no matter what I do?
     ahk_do "
         winwait Blizzard Updater v2.72
         send {Enter}
         winwait Diablo II
         ControlClick &Cancel, Diablo II"
+    # Dagnabbit, the darn updater starts the game after it updates, no matter what I do?
+    killall "Game.exe"
 
     warn "When starting the game, be patient, wait until the menu appears.  The game seems to hang if it looses focus, see bug 14456, you may need to set winecfg to virtual desktop."
 }
@@ -1211,6 +1314,15 @@ load_gta_vc() {
 
 #----------------------------------------------------------------
 
+verblist_add help     "How to use this tool"
+
+load_help() {
+    warn "If the game is not marked with {download} or {loaded} in the menu, you have to insert its disc and give the 'load' command before you can choose that game in the menu.  If the game has multiple discs, you have to do this for each disc."
+    warn "If the game has an install key, you have to enter that when loading the first disc.  (You have to do that from the commandline, e.g. sh wisotool load=XXXX-YYYY-ZZZZ.)"
+}
+
+#----------------------------------------------------------------
+
 verblist_add morrowind     "The Elder Scrolls III: Morrowind (Bethesda, 2002)" \
   c8368ed30d3f3fcd7fccf8bffcfcdf0a6d4cb68b.iso
 
@@ -1261,7 +1373,7 @@ sed -e 's/$/\r/' morrowind.tmp > morrowind.ahk
 
 #----------------------------------------------------------------
 
-verblist_add pcmark04 "PC Mark 04 (Futuremark, 2004)" PCMark04_v130_installer.exe
+verblist_add pcmark04 "PC Mark 04 (Futuremark, 2004) [download]" PCMark04_v130_installer.exe
 
 load_pcmark04() {
     load_autohotkey
@@ -1314,7 +1426,7 @@ load_pcmark04() {
 
 #----------------------------------------------------------------
 
-verblist_add pcmark05 "PC Mark 05 (Futuremark, 2005)" PCMark05_v130_1901.exe
+verblist_add pcmark05 "PC Mark 05 (Futuremark, 2005) [download]" PCMark05_v130_1901.exe
 
 load_pcmark05() {
     load_autohotkey
@@ -1365,7 +1477,8 @@ load_pcmark05() {
 
 #----------------------------------------------------------------
 
-verblist_add passmark7 "Performance Test 7 (Passmark, 2010)" petst.exe
+# Not finished
+#verblist_add passmark7 "Performance Test 7 (Passmark, 2010) [download]" petst.exe
 
 load_passmark7() {
     load_autohotkey
@@ -1385,7 +1498,7 @@ load_passmark7() {
 
 #----------------------------------------------------------------
 
-verblist_add plantsvszombies "Plants vs. Zombies (PopCap Games, 2009)" PlantsVsZombiesSetup.exe
+verblist_add plantsvszombies "Plants vs. Zombies (PopCap Games, 2009) [download]" PlantsVsZombiesSetup.exe
 
 load_plantsvszombies() {
     load_autohotkey
@@ -1410,7 +1523,7 @@ load_plantsvszombies() {
 
 #----------------------------------------------------------------
 
-verblist_add re5bench "Resident Evil 5 Benchmark (Capcom, 2009)" nzd_ResidentEvil5_Benchmark.exe
+verblist_add re5bench "Resident Evil 5 Benchmark (Capcom, 2009) [download]" nzd_ResidentEvil5_Benchmark.exe
 
 load_re5bench() {
     load_autohotkey
@@ -1424,7 +1537,9 @@ load_re5bench() {
     ahk_do "
         run nzd_ResidentEvil5_Benchmark.exe
         WinWait ahk_class MsiDialogCloseClass 
-        ControlClick Button1 ; Next
+        Sleep 1000
+        Send {Enter}
+        ; ControlClick Button1 ; Next.  Doesn't work?
         WinWait ahk_class MsiDialogCloseClass, License
         ControlClick Button3 ; Accept
         ControlClick Button5 ; Next
@@ -1524,23 +1639,22 @@ load_sims3() {
         ControlClick Finish, - InstallShield Wizard
     "
     iso_umount
+
     cd "$programfilesdir_unix/Electronic Arts/The Sims 3/Game/Bin"
-    
-    currentversion=$(head -n 1 skuversion.txt | awk '{print $3}' | tr -d '\r\n')
-    # FIXME: Find a way of determining the newest version from ea.com. The below code works, but the xml is outdated, and returns 1.4.6.00002. For now, hardcode it.
-    # newestversion=$(wget -O - http://na.llnet.eadownloads.ea.com/u/f/sims/sims3/patches/sims3_sku2_update_manifest.xml | grep NewVersion= | head -n1 | awk -F\" '{print $2}')
-    # FIXME: include a table of sha1sums so we can check the download
-    newestversion=1.6.6.002001
-    download sims3 http://na.llnet.eadownloads.ea.com/u/f/sims/sims3/patches/Sims3_${newestversion}_from_${currentversion}.exe
+    echo "Sims3 version info:"
+    cat skuversion.txt
+
+    download sims3 http://na.llnet.eadownloads.ea.com/u/f/sims/sims3/patches/Sims3_1.6.6.002001_from_1.0.631.00001.exe 02703d296417750005326ff0d37295fa434a3f49
 
     cd "$WISOTOOL_CACHE"/sims3
     ahk_do "
-        run Sims3_${newestversion}_from_${currentversion}.exe
+        run Sims3_1.6.6.002001_from_1.0.631.00001.exe
         SetTitleMatchMode, 2
         winwait, - InstallShield Wizard, Complete
         ControlClick Finish, - InstallShield Wizard
     "
 
+    # FIXME: apply next patch, too
 }
 
 #----------------------------------------------------------------
@@ -1635,6 +1749,7 @@ load_stfu() {
     load_autohotkey
 
     iso_mount "$WISOTOOL_CACHE"/$PACKAGE/0d0f4e826c3a04542a68d7bcc971f4df7526965b.iso
+    warn "Starting installer.  This can be very slow, please be patient."
     ahk_do "
         run ${ISO_MOUNT_LETTER}:setup.exe
         SetTitleMatchMode, 2
@@ -1662,7 +1777,9 @@ load_stfu() {
         SetTitleMatchMode, 2
         send {Enter}
         winwait, Setup, Completing
-        ControlClick Finish
+        send {Space}{Tab} ; don't show readme
+        send {Space}{Tab} ; don't start app
+        send {Enter}
     "
     iso_umount
 
@@ -1677,14 +1794,14 @@ load_stfu() {
         SetTitleMatchMode, 2
         winwait, Patch
         send {Enter}
-        winwait, Patch, Successful
+        winwait, Patch, Finish
         send {Enter}
     "
 }
 
 #----------------------------------------------------------------
 
-verblist_add unigine_heaven "Unigen Heaven 2 Benchmark (Unigen, 2010)" Unigine_Heaven-2.0.msi 6a0bd499ae8ed8d73d74d964d3c4312a0a40b7e6
+verblist_add unigine_heaven "Unigen Heaven 2 Benchmark (Unigen, 2010) [download]" Unigine_Heaven-2.0.msi 6a0bd499ae8ed8d73d74d964d3c4312a0a40b7e6
 
 load_unigine_heaven() {
     load_autohotkey
@@ -1700,6 +1817,7 @@ load_unigine_heaven() {
     ahk_do "
         run msiexec /i Unigine_Heaven-2.0.msi
         WinWait ahk_class MsiDialogCloseClass 
+        Sleep 1000
         Send {Enter}
         WinWait ahk_class MsiDialogCloseClass, License
         ControlClick Button1 ; Accept
@@ -1719,7 +1837,7 @@ load_unigine_heaven() {
 
 #----------------------------------------------------------------
 
-verblist_add wog           "World of Goo demo (2D Boy, 2008)" WorldOfGooDemo.1.0.exe
+verblist_add wog           "World of Goo demo (2D Boy, 2008) [download]" WorldOfGooDemo.1.0.exe
 
 load_wog() {
     load_autohotkey
